# Generated by Django 5.2.7 on 2025-10-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name e.g. Mumbai', max_length=128)),
                ('email', models.EmailField(blank=True, help_text='Optional: notify this email', max_length=254, null=True)),
                ('last_temp', models.FloatField(blank=True, null=True)),
                ('last_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('periodic_task_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
